# Install pacman package if needed ----
# install.packages('pacman')

# Load required packages ----
NPacks <- c("tidyverse", "readxl", "here", "GCalignR")
pacman::p_load(char = NPacks)

# FUNCTIONS ----
## A function to load CSV generated by MassHunterQual with lapply
my_read_csv  <- function(file, skip) {
  skip = 2
  read_csv(file = file, skip = skip)
}

# Import data files ----
## Make a list of the individual sample files paths
### Week 1 nurses (W1_Nu)
path_W1_Nu_data <- list.files(path = here("data", "raw", "queen-less"
                              , "gcms-integration-files", "week_1", "Nu")
                              , pattern = ".CSV" # Get all CSV files in the folder
                              , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_W1_Nu_data

### Week 3 elongated abdomen in-hive workers (W3_EIW)
path_W3_EIW_data <- list.files(path = here("data", "raw", "queen-less"
                              , "gcms-integration-files", "week_3", "EIW")
                              , pattern = ".CSV" # Get all CSV files in the folder
                              , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_W3_EIW_data

### Week 3 in-hive workers (W3_NIW)
path_W3_NIW_data <- list.files(path = here("data", "raw", "queen-less"
                                          , "gcms-integration-files"
                                          , "week_3"
                                          , "NIW")
                              , pattern = ".CSV" # Get all CSV files in the folder
                              , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_W3_NIW_data

### Standards (STD)
# path_standards <- list.files(path = here("data", "raw", "NM-recognition"
#                                          , "gcms-integration-files"
#                                          , "standards")
#                              , pattern = ".CSV" # Get all CSV files in the folder
#                              , full.names = T) %>% 
#   str_subset('DR_', negate = T) # Do not include samples
# path_standards

## Import the files in the list, saving them into a list type object
### W1_Nu
W1_Nu_data_list <- lapply(path_W1_Nu_data, my_read_csv)
W1_Nu_data_list %>% summary()

## W3_EIW
W3_EIW_data_list <- lapply(path_W3_EIW_data, my_read_csv)
W3_EIW_data_list %>% summary()

## W3_NIW
W3_NIW_data_list <- lapply(path_W3_NIW_data, my_read_csv)
W3_NIW_data_list %>% summary()

## STD
# standards_list <- lapply(path_standards, my_read_csv)
# standards_list %>% summary()

# Rename the data frames in the list as the samples to which they belong ----
## W1_Nu
names(W1_Nu_data_list) <- str_split(path_W1_Nu_data
                                    , "/"
                                    , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("DR_") %>% 
  str_remove(".CSV") 
names(W1_Nu_data_list)

## W3_EIW
names(W3_EIW_data_list) <- str_split(path_W3_EIW_data
                                    , "/"
                                    , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("DR_") %>% 
  str_remove(".CSV") 
names(W3_EIW_data_list)

## W3_NIW
names(W3_NIW_data_list) <- str_split(path_W3_NIW_data
                                    , "/"
                                    , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("DR_") %>% 
  str_remove(".CSV") 
names(W3_NIW_data_list)

## STD
# names(standards_list) <- str_split(path_standards
#                                    , "/"
#                                    , simplify = T) %>% 
#   str_subset(".CSV") %>% 
#   str_remove("STD") %>% 
#   #str_remove("STDL") %>% 
#   str_remove(".CSV") 
# names(standards_list)

# Modify data frames to keep the necessary columns ----
## W1_Nu
names(W1_Nu_data_list)
W1_Nu_data_list %>% summary()
W1_Nu_sample.names <- names(W1_Nu_data_list)
#W1_Nu_data_list[[eval(W1_Nu_sample.names[1])]]
for (df in W1_Nu_sample.names) {
  W1_Nu_data_list[[df]] <- W1_Nu_data_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
  #assign(df, df_n)
  #rm(df, df_n)
}
W1_Nu_data_list %>% summary()

## W3_EIW
names(W3_EIW_data_list)
W3_EIW_data_list %>% summary()
W3_EIW_sample.names <- names(W3_EIW_data_list)
#W3_EIW_data_list[[eval(W3_EIW_sample.names[1])]]
for (df in W3_EIW_sample.names) {
  W3_EIW_data_list[[df]] <- W3_EIW_data_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
  #assign(df, df_n)
  #rm(df, df_n)
}
W3_EIW_data_list %>% summary()

## W3_NIW
names(W3_NIW_data_list)
W3_NIW_data_list %>% summary()
W3_NIW_sample.names <- names(W3_NIW_data_list)
#W3_NIW_data_list[[eval(W3_NIW_sample.names[1])]]
for (df in W3_NIW_sample.names) {
  W3_NIW_data_list[[df]] <- W3_NIW_data_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
  #assign(df, df_n)
  #rm(df, df_n)
}
W3_NIW_data_list %>% summary()

# ## STD
# names(standards_list)
# standards_list %>% summary()
# standards.names <- names(standards_list)
# #standards_list[[eval(standards_sample.names[1])]]
# for (df in standards.names) {
#   standards_list[[df]] <- standards_list[[df]] %>% 
#     select("Center X", "Area") %>% 
#     rename(RT = "Center X")
# }
# standards_list %>% summary()


# Input check-up for GCalignR ----
pdf(here("output"
         , "queen-less"
         , paste0("GCalignR_input-check_PL_"
                  , "QLH"
                  , '.pdf'))
    , width = 10, height = 5)

## list ####
#check_input(list, plot = T)
#peak_interspace(list
#               , rt_col_name = "RT"
#              , quantile_range = c(0, 0.8)
#             , quantiles = 0.05)

## list ####
#check_input(list, plot = T)
#peak_interspace(list
#               , rt_col_name = "RT"
#              , quantile_range = c(0, 0.8)
#             , quantiles = 0.05)

#### Close graphic device to export plots into the PDF file
dev.off()
print("Input check-up plots were exported")


# Export data ----
## W1_Nu
save(list = c("W1_Nu_data_list", "W3_EIW_data_list"
              , "W3_NIW_data_list")
     , file = here("data", "raw", "queen-less", "tmp", "data2align.Rdata"))

print("The data list(s) to align have been exported to the tmp data folder")

# End ----
## Report session information
capture.output(sessionInfo()
               , file = here("output", "queen-less", "SInf_QLH_Script01.txt"))

# ## Detach/unload packages
# lapply(NPacks, unloadNamespace)
# 
# ## Clear environment
# rm(list=ls())

