# Install pacman package if necessary ----
#install.packages("pacman")

# Load required packages ----
NPacks <- c("readr", "stringr","tidyr", "dplyr", "here")
pacman::p_load(char = NPacks)

# FUNCTIONS ----
## A function to load CSV generated by MassHunterQual with lapply
my_read_csv  <- function(file, skip) {
  skip = 2
  read_csv(file = file, skip = skip)
}

# Import data files ----
## Make a list of the gcms integration files path
path_gcms_integration_data <- list.files(path = here("data", "raw", "queen-less"
                                          , "gcms-integration-files")
                              , pattern = ".CSV" # Get all CSV files in the folder
                              , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_gcms_integration_data

## Import the files in the list, saving them into a list type object
gcms_integration_data_list <- lapply(path_gcms_integration_data, my_read_csv)
gcms_integration_data_list %>% summary()

## Load group membership information
sample_info <- read_csv(here("data"
                             , "raw"
                             , "queen-less"
                             , "Queenless_hive_table.csv"))
sample_info

factors <- c("Task", "Date")

sample_info <- sample_info %>% 
                mutate(group_label = paste(sample_info %>% select(all_of(factors)), collapse = "_"))
sample_info

