# Install pacman package if needed ----
# install.packages('pacman')

# Load required packages ----
NPacks <- c("tidyverse", "readxl", "here")
pacman::p_load(char = NPacks)

# FUNCTIONS ----
## A function to load CSV generated by MassHunterQual with lapply
my_read_csv  <- function(file, skip) {
  skip = 2
  read_csv(file = file, skip = skip)
}

# Import data files ----
## Make a list of the individual sample files paths
### In-hive workers (IW)
path_IW_data <- list.files(path = here("AMelliMelli-CHC-data", "raw", "IW")
                                   , pattern = ".CSV" # Get all CSV files in the folder
                                   , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_IW_data

### Out-hive workers (OW)
path_OW_data <- list.files(path = here("AMelliMelli-CHC-data", "raw", "OW")
                                   , pattern = ".CSV" # Get all CSV files in the folder
                                   , full.names = T) %>% 
  str_subset('STD', negate = T) # Do not include standards
path_OW_data

### Standards (STD)
path_standards <- list.files(path = here("AMelliMelli-CHC-data", "raw", "STD")
                             , pattern = ".CSV" # Get all CSV files in the folder
                             , full.names = T) %>% 
  str_subset('DR_', negate = T) # Do not include samples
path_standards

## Import the files in the list, saving them into a list type object
### IW
IW_data_list <- lapply(path_IW_data, my_read_csv)
IW_data_list %>% summary()

## OW
OW_data_list <- lapply(path_OW_data, my_read_csv)
OW_data_list %>% summary()

## STD
standards_list <- lapply(path_standards, my_read_csv)
standards_list %>% summary()

# Rename the data frames in the list as the samples to which they belong ----
## IW
names(IW_data_list) <- str_split(path_IW_data
                                     , "/"
                                     , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("DR_") %>% 
  str_remove(".CSV") 
names(IW_data_list)

## OW
names(OW_data_list) <- str_split(path_OW_data
                                         , "/"
                                         , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("DR_") %>% 
  str_remove(".CSV") 
names(OW_data_list)

## STD
names(standards_list) <- str_split(path_standards
                                   , "/"
                                   , simplify = T) %>% 
  str_subset(".CSV") %>% 
  str_remove("STD") %>% 
  #str_remove("STDL") %>% 
  str_remove(".CSV") 
names(standards_list)

# Modify data frames to keep the necessary columns ----
## IW
names(IW_data_list)
IW_data_list %>% summary()
IW_sample.names <- names(IW_data_list)
#IW_data_list[[eval(IW_sample.names[1])]]
for (df in IW_sample.names) {
  IW_data_list[[df]] <- IW_data_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
  #assign(df, df_n)
  #rm(df, df_n)
}
IW_data_list %>% summary()

## OW
names(OW_data_list)
OW_data_list %>% summary()
OW_sample.names <- names(OW_data_list)
#OW_data_list[[eval(OW_sample.names[1])]]
for (df in OW_sample.names) {
  OW_data_list[[df]] <- OW_data_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
  #assign(df, df_n)
  #rm(df, df_n)
}
OW_data_list %>% summary()

## STD
names(standards_list)
standards_list %>% summary()
OW_standards.names <- names(standards_list)
#standards_list[[eval(OW_sample.names[1])]]
for (df in OW_standards.names) {
  standards_list[[df]] <- standards_list[[df]] %>% 
    select("Center X", "Area") %>% 
    rename(RT = "Center X")
}
standards_list %>% summary()

# Export data ----
## IW
save(list = c("IW_data_list", "OW_data_list", "standards_list")
     , file = here("AMelliMelli-CHC-data", "tmp", "data2align.Rdata"))

print("The data list(s) to align have been exported to the tmp data folder")

# End ----
## Report session information
capture.output(sessionInfo()
               , file = here("output", "SInf_Script01.txt"))

# ## Detach/unload packages
# lapply(NPacks, unloadNamespace)
# 
# ## Clear environment
# rm(list=ls())

